alias: openhasp cover art plate35
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.spotify_smarthome1
condition:
  - condition: template
    value_template: |
      {{ trigger.from_state.attributes.entity_picture !=
         trigger.to_state.attributes.entity_picture }}
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ state_attr('media_player.spotify_smarthome1','entity_picture')
              != None }}
        sequence:
          - service: openhasp.push_image
            target:
              entity_id: openhasp.plate35
            data:
              image: >-
                http://192.168.2.47:8123{{
                state_attr('media_player.spotify_smarthome1','entity_picture')
                }}
              obj: p4b51
              width: 235
              height: 250
          - service: openhasp.command
            data:
              keyword: p4b50.hidden
              parameters: "0"
            target:
              entity_id: openhasp.plate35
      - conditions:
          - condition: template
            value_template: >-
              {{ state_attr('media_player.spotify_smarthome1','entity_picture')
              == None }}
        sequence:
          - service: openhasp.command
            data:
              keyword: p4b50.hidden
              parameters: "1"
            target:
              entity_id: openhasp.plate35
mode: single
